-- 1 Count rides in every city.
SELECT city_name , count(ride_id) AS riders FROM rides JOIN cities 
ON rides.city_id = cities.city_id GROUP BY cities.city_id ;

-- 2 count users in every city.
select city_name , COUNT(user_id) as total_users from users join cities 
on users.city_id = cities.city_id group by city_name ;

-- 3 Show all rides that were cancelled.
select * from rides where ride_status="cancelled";

-- 4 Find drivers who have a rating above 4.5.
select name , driver_id  , rating FROM drivers  WHERE rating > 4.5;

-- 5 Find users who have completed more than 100 rides. 
select name , user_id, total_rides FROM users WHERE total_rides > 100;

-- 6 . Find the average fare for rides. 
SELECT avg(total_fare) AS total_avg_fare FROM rides ;

-- 7 Top 10 highest spending users. 
select users.user_id , users.name , sum(rides.total_fare) AS total_spend from users join rides 
on users.user_id = rides.user_id group by users.user_id,users.name 
ORDER BY total_spend DESC
LIMIT 10;

-- 8 Find users who never booked a ride.
select users.user_id, users.name from users left join rides 
on users.user_id = rides.user_id group by users.user_id;

-- 9 Find the total revenue generated by each city. 
select cities.city_name , SUM(rides.total_fare) AS total_revenue FROM rides join cities 
ON rides.city_id= cities.city_id group by city_name ORDER BY total_revenue DESC ;

-- 10 Find the average ride distance for each city. 
SELECT AVG(distance_km) AS average_ride_distance , cities.city_name FROM rides JOIN cities 
on rides.city_name=cities,city_name GROUP BY cities.city_name ;

-- 11 Find the total rides completed by each driver. 
select drivers.name , drivers.driver_id , COUNT(rides.ride_id) AS total_rides from rides join drivers 
on drivers.driver_id= rides.driver_id ORDER BY total_rides DESC ;

-- 12 Find the most popular payment mode. 
SELECT payment_mode , amount , COUNT(*) AS total_transactions FROM rides
GROUP BY payment_mode ORDER BY total_transactions DESC
LIMIT 1;

-- 14 Which vehicle brand generates the highest revenue?
select vehicles.make , vehicles.year , SUM(rides.total_fare) AS total_revenue 
from rides join vehicles  on rides.vehicle_id=vehicles.vehicle_id group by vehicles.make,vehicles.year
order by total_revenue DESC 
LIMIT 1;

-- 15 Highest earning city and driver together.
SELECT cities.city_name , drivers.name , SUM(payments.amount) AS revenue FROM rides 
JOIN drivers ON rides.driver_id= drivers.driver_id 
JOIN cities ON rides.city_id=cities.city_id
JOIN payments ON rides.ride_id=payments.ride_id
GROUP BY cities.city_name,drivers.name
ORDER BY revenue DESC;

-- 16 Find the cancellation percentage of rides.
SELECT
ROUND(
    COUNT(CASE WHEN ride_status = 'cancelled' THEN 1 END)
    * 100.0 / COUNT(*), 2
) AS cancellation_percentage
FROM rides;

-- 17 Find the city with the highest average surge multiplier.
SELECT c.city_name,
       AVG(r.surge_multiplier) AS average_surge
FROM rides r
JOIN cities c
ON r.city_id = c.city_id
GROUP BY c.city_name
ORDER BY average_surge DESC
LIMIT 1;

-- 18 find the drivers whose cancellation rates is higher than the average cancellation rate of all the drivers.
SELECT driver_id,
       name,
       cancellation_rate
FROM drivers
WHERE cancellation_rate >
(
    SELECT AVG(cancellation_rate)
    FROM drivers
);

-- 19 Find the top 5 users based on their total spending.
SELECT 
    u.user_id, 
    u.user_name, 
    SUM(o.amount) AS total_spending
FROM users u
JOIN orders o ON u.user_id = o.user_id
GROUP BY u.user_id, u.user_name
ORDER BY total_spending DESC
LIMIT 5;

-- 20 Categorize rides into 'Short', 'Medium', and 'Long' distance tiers.
SELECT ride_id, distance_km,
       CASE 
           WHEN distance_km < 5 THEN 'Short'
           WHEN distance_km BETWEEN 5 AND 15 THEN 'Medium'
           ELSE 'Long'
       END AS distance_category
FROM rides;

Select COUNT(*) AS total_users 
FROM users;
Select COUNT(*) AS total_city
FROM cities;